name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            script: npm run dist:win
          - os: macos-latest
            script: npm run dist:mac
          - os: ubuntu-latest
            script: npm run dist:linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: ${{ matrix.script }} -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
